idf_component_register(SRCS 
                        "main.c" 
                        "i2s_mic.c"
                        "kiss_fft.c"
                        "mfcc.c"
                        "model_data.cc"
                        "inference.cc"
                        "mqtt.c"
                        "wifi.c"
                    INCLUDE_DIRS ".")
